#SPLIT_KEYBOARD = yes
#SPLIT_TRANSPORT = serial
SERIAL_DRIVER = vendor

#EEPROM_ENABLE = yes
#BOOTMAGIC_ENABLE = yes
POINTING_DEVICE_DRIVER = pmw3360
AUDIO_SUPPORTED = no
CONSOLE_ENABLE = yes
#BOOTLOADER = rp2040
#MCU = RP2040
